# Generated by Django 5.2.4 on 2025-08-14 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-fecha_publicacion']},
        ),
        migrations.RenameField(
            model_name='page',
            old_name='contenido',
            new_name='cuerpo',
        ),
        migrations.RemoveField(
            model_name='page',
            name='resumen',
        ),
        migrations.AddField(
            model_name='page',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='bajada',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='page',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
