# Generated by Django 5.2.4 on 2025-08-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_local_ropa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenda',
            name='marca',
        ),
        migrations.AddField(
            model_name='prenda',
            name='color',
            field=models.CharField(default='Sin especificar', max_length=50),
        ),
    ]
