# Generated by Django 5.2.4 on 2025-08-14 11:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_local_ropa', '0002_remove_prenda_marca_prenda_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
